# Generated by Django 4.2.5 on 2023-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('operatingdate', models.CharField(max_length=100)),
                ('airline', models.CharField(max_length=100)),
                ('airlinenumber', models.IntegerField()),
                ('departureport', models.CharField(max_length=100)),
                ('arrivalport', models.CharField(max_length=100)),
                ('departuredateandtime', models.CharField(max_length=100)),
                ('arrivaldateandtime', models.CharField(max_length=100)),
                ('flightstatus', models.CharField(max_length=100)),
                ('delayissues', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fligt', models.CharField(max_length=100)),
                ('servicestatus', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('departureport', models.CharField(max_length=100)),
                ('arrivalport', models.CharField(max_length=100)),
                ('departuredateandtime', models.CharField(max_length=100)),
                ('arrivaldateandtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journeysearch',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('flightname', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('departuredateandtime', models.CharField(max_length=100)),
                ('arrivaldateandtime', models.CharField(max_length=100)),
                ('riskstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Riskaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Travella',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('flight', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nrc', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('departureport', models.CharField(max_length=100)),
                ('departuredateandtime', models.CharField(max_length=100)),
                ('arrivalport', models.CharField(max_length=100)),
                ('arrivaldateandtime', models.CharField(max_length=100)),
            ],
        ),
    ]
